[package]
name = "flightsql"
version = "0.1.0"
edition = "2024"

[dependencies]
adbc_core = "0.20.0"
adbc_driver_manager = "0.20.0"
arrow = { version = "56.2.0", features = ["prettyprint"] }
arrow-array = "56.2.0"
